### ISSUE TITLE
Library doesn't work with new redux version

### ISSUE THREAD

**Issue by kataRebuy** [reduxkotlin/Reselect#11]
I tried to update the redux library to:  `implementation "org.reduxkotlin:redux-kotlin-threadsafe-jvm:0.6.1"`
After the update, I get the following runtime crash
```
 java.lang.NoSuchMethodError: No static method selectors(Lorg/reduxkotlin/TypedStore;Lkotlin/jvm/functions/Function1;)Lkotlin/jvm/functions/Function0; in class Lorg/reduxkotlin/ReselectKt; or its super classes (declaration of 'org.reduxkotlin.ReselectKt' appears in /data/app/~~r_RloHQCj83ZeCM7XSwB_Q==/my.package.name-G5JaxuquUCQcKetvAwK92A==/base.apk!classes22.dex)
    	at my.package.name.MainActivity.onStart(MainActivity.kt:156)
    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
    	at android.app.Activity.performStart(Activity.java:8330)
    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    	at android.os.Handler.dispatchMessage(Handler.java:106)
    	at android.os.Looper.loopOnce(Looper.java:201)
    	at android.os.Looper.loop(Looper.java:288)
    	at android.app.ActivityThread.main(ActivityThread.java:7872)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 ```
 
 The crash happens when I call the `selectors` extension function like this:
```
val multiSubscription = store.selectors {
            select({ it.isLoading }) {
                loadingIndicator.visibility = if (store.state.isLoading) View.VISIBLE else View.GONE
            }
            select({ it.name }) {
                nameTextView.text = store.state.name
            }
        }
```

**Comment by eoinfogarty** [comment]
I am also getting this too. I think the internal version of the redux library this library uses needs to be bumped.

https://github.com/reduxkotlin/Reselect/blob/fbb3783b9c153f65e49af9d17f4976c184ae6ed9/buildSrc/src/main/kotlin/Versions.kt#L27

**Comment by mpetuska** [comment]
Hi both, unfortunately I'm unable to upgrade reselect module as I did the others due to missing access to this repo. I'll try to get a hold of the owner to sort it out in the near future, but for now don't upgrade to redux 0.6.x if you depend on reselect. Apologies for the confusion.
